"""
tests/test_validation_schema.py
================================
Verifies that reports/validation_report.json conforms to the schema v1.0
generated by evaluate.py (Phase 6 Task 3 schema freeze).

Actual schema structure:
{
  "schema_version": "1.0",
  "provenance": {
    "model_version": <str>,
    "checkpoint_sha256": <str>,
    "generated_at": <str>,
    "seed": <int>,
    "device": <str>,
    "split_sizes": {"train": int, "val": int, "test": int}
  },
  "dataset": { ... },
  "metrics": {
    "test": {
      "calibrated": {
        "n": int, "accuracy": float, "recall": float, "auroc": float, ...
      },
      "uncalibrated": { ... }
    },
    "val": { ... }
  },
  "calibration": { "temperature": float, ... },
  "selective": {
    "test": {
      "tau_accept": float, "tau_low_uncertainty": float,
      "coverage": float, "accepted_accuracy": float, ...
    }
  },
  "quality_eval": { ... },
  "ood_eval": { ... },
  "limitations": [str, ...]
}
"""
import json
from pathlib import Path
import pytest
import sys

_ML_ROOT = Path(__file__).resolve().parent.parent
if str(_ML_ROOT) not in sys.path:
    sys.path.insert(0, str(_ML_ROOT))

from config import REPORTS_DIR  # noqa: E402

REPORT_PATH = REPORTS_DIR / "validation_report.json"


@pytest.fixture(scope="module")
def report():
    if not REPORT_PATH.exists():
        pytest.skip(f"Validation report not found at {REPORT_PATH}")
    with open(REPORT_PATH, "r", encoding="utf-8") as f:
        return json.load(f)


# ─── Top-level structure ─────────────────────────────────────────────────────

REQUIRED_TOP_KEYS = [
    "schema_version", "provenance", "dataset", "metrics",
    "calibration", "selective", "limitations",
]


def test_top_level_keys_present(report):
    for key in REQUIRED_TOP_KEYS:
        assert key in report, f"Missing top-level key: '{key}'"


def test_schema_version_is_1(report):
    sv = report.get("schema_version")
    # Accept "1", "1.0" — the freeze is the structure, not the exact string
    assert sv in ("1", "1.0"), f"Unexpected schema_version: {sv!r}"


# ─── Provenance ──────────────────────────────────────────────────────────────

REQUIRED_PROVENANCE_KEYS = [
    "model_version", "checkpoint_sha256", "generated_at", "seed", "device", "split_sizes"
]


def test_provenance_keys_present(report):
    prov = report.get("provenance", {})
    for key in REQUIRED_PROVENANCE_KEYS:
        assert key in prov, f"Missing provenance key: '{key}'"


def test_provenance_types(report):
    prov = report["provenance"]
    assert isinstance(prov["model_version"], str)
    assert isinstance(prov["generated_at"], str)
    assert isinstance(prov["seed"], int)
    assert isinstance(prov["split_sizes"], dict)
    assert prov["split_sizes"].get("test", 0) > 0, "split_sizes.test must be > 0"


# ─── Metrics ─────────────────────────────────────────────────────────────────

REQUIRED_CALIBRATED_METRIC_KEYS = [
    "n", "accuracy", "precision", "recall", "sensitivity", "specificity",
    "f1", "auroc",
]


def test_metrics_test_split_present(report):
    metrics = report.get("metrics", {})
    assert "test" in metrics, "metrics.test is missing"
    test_m = metrics["test"]
    for sub in ("calibrated", "uncalibrated"):
        assert sub in test_m, f"metrics.test.{sub} is missing"


def test_metrics_calibrated_keys_present(report):
    cal = report["metrics"]["test"]["calibrated"]
    for key in REQUIRED_CALIBRATED_METRIC_KEYS:
        assert key in cal, f"Missing metrics.test.calibrated key: '{key}'"


def test_metrics_values_in_range(report):
    cal = report["metrics"]["test"]["calibrated"]
    for key in ("accuracy", "precision", "recall", "sensitivity", "specificity", "f1", "auroc"):
        val = cal.get(key)
        if val is not None:
            assert 0.0 <= val <= 1.0, f"metrics.test.calibrated.{key}={val} out of [0,1]"


def test_n_test_positive(report):
    n = report["metrics"]["test"]["calibrated"].get("n")
    assert isinstance(n, int) and n > 0, f"metrics.test.calibrated.n must be positive int, got {n!r}"


# ─── Calibration ─────────────────────────────────────────────────────────────

def test_calibration_temperature_present(report):
    cal = report.get("calibration", {})
    assert "temperature" in cal, "calibration.temperature is missing"
    assert isinstance(cal["temperature"], (int, float)), "calibration.temperature must be numeric"


# ─── Selective prediction (abstention) ───────────────────────────────────────

REQUIRED_SELECTIVE_KEYS = [
    "tau_accept", "tau_low_uncertainty", "coverage", "accepted_accuracy",
]


def test_selective_test_keys(report):
    sel = report.get("selective", {}).get("test", {})
    for key in REQUIRED_SELECTIVE_KEYS:
        assert key in sel, f"Missing selective.test key: '{key}'"


def test_selective_coverage_in_range(report):
    cov = report["selective"]["test"].get("coverage")
    if cov is not None:
        assert 0.0 <= cov <= 1.0, f"selective.test.coverage={cov} out of [0,1]"


# ─── Limitations ─────────────────────────────────────────────────────────────

def test_limitations_non_empty_list_of_strings(report):
    lims = report.get("limitations", [])
    assert len(lims) > 0, "limitations must be a non-empty list"
    for i, lim in enumerate(lims):
        assert isinstance(lim, str), f"limitations[{i}] must be a string, got {type(lim).__name__}"


# ─── JSON serializability ─────────────────────────────────────────────────────

def test_report_is_json_serializable(report):
    out = json.dumps(report)
    assert len(out) > 0
